"""Initial migration

Revision ID: 113c5d3c52e4
Revises: 
Create Date: 2025-10-01 07:35:53.811344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '113c5d3c52e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Job_Listings',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('salary_range', sa.String(length=100), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('posting_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('referral_bonus', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('external_job_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('Referrals',
    sa.Column('referral_id', sa.String(length=36), nullable=False),
    sa.Column('referrer_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('applicant_email', sa.String(length=255), nullable=False),
    sa.Column('applicant_name', sa.String(length=255), nullable=False),
    sa.Column('referral_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('commission_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('commission_paid', sa.Boolean(), nullable=True),
    sa.Column('applicant_phone', sa.String(length=20), nullable=True),
    sa.Column('applicant_linkedin', sa.String(length=255), nullable=True),
    sa.Column('resume_path', sa.String(length=500), nullable=True),
    sa.Column('interview_date', sa.DateTime(), nullable=True),
    sa.Column('hired_date', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('zoho_candidate_id', sa.String(length=100), nullable=True),
    sa.Column('zoho_application_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['Job_Listings.job_id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('referral_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Referrals')
    op.drop_table('Job_Listings')
    op.drop_table('Users')
    # ### end Alembic commands ###
